# Generated by Django 4.2.13 on 2024-05-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='description',
            field=models.CharField(blank=True, help_text='편의시설에 대한 설명을 입력하세요. (선택 사항)', max_length=150, null=True, verbose_name='편의시설 설명'),
        ),
    ]
