# Generated by Django 4.2.13 on 2024-05-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_amenity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='', help_text='숙소 이름을 입력하세요.', max_length=150, verbose_name='숙소 이름'),
        ),
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(default='', help_text='숙소에 편의시설을 선택하세요.', to='rooms.amenity', verbose_name='편의시설'),
        ),
    ]
